<?php

return [

    'MAX_ITEMS_PER_PAGE'          => 10,
    'API_MAX_ITEMS_PER_PAGE'      => 25,
    'MAX_CALENDAR_ITEMS_PER_PAGE' => 100,
    'TRIP_TIME'                   => '10:00:00',
    'SEGMENT_SIZE'                => '00:30',
    'STRIPE_AUTHORIZE_URL'        => 'https://connect.stripe.com/oauth/authorize',
    'STRIPE_CLIENT_ID'            => 'ca_HCwzFkjC27mpK21dOLNLtB93S7UeaRnp',
    'STRIPE_RESPONSE_TYPE'        => 'code',
    'STRIPE_RESPONSE_SCOPE'       => 'read_write',
    'MOVE_PAYMENT_DUE_DAYS'       => 4,
    'MUVAL_SUPPORT_ADDRESS'       => 'support@muval.com.au',
    'ACCESS_SURCHARGES'           => 0,
    'ACCESS_WORK_RATE_PICKUP'     => 7,
    'ACCESS_WORK_RATE_DELIVERY'   => 9,
    'ACCESS_DRIVEWAY'             => 'driveway',
    'ACCESS_STAIRS'               => 'stairs',
    'ACCESS_ELEVATOR'             => 'elevator',
    'ACCESS_PARKING'              => 'no parking',
    'DEPOT_SPACE_VALUE'           => 3,
    'MOVE_HOT_STATUS_ID'          => 8,
    'MOVE_COLD_STATUS_ID'         => 9,
    'MOVE_DECLINED_STATUS_ID'     => 10,
    'MOVE_CONTACTED_STATUS_ID'    => 11,
    'MOVE_PENDING_STATUS_ID'      => 12,
    'MOVE_ACCEPTED_STATUS_ID'     => 13,
    'MOVE_DEPOSIT_PAID_STATUS_ID' => 14,
    'MOVE_COMPLETED_STATUS_ID'    => 15,
    'TRANSPORT_RAIL'              => 2,
    'TRANSPORT_TRUCK'             => 1,

];
