<?php
return [
    "Bedroom" => array(
        "bassinette" => array("title" => "Bassinette", "volume" => 0.25, "synonyms" => "cradle,cot"),
        "king_mattress" => array("title" => "King Mattress", "volume" => 1),
        "double_mattress" => array("title" => "Double Mattress", "volume" => 0.6),
        "queen_mattress" => array("title" => "Queen Mattress", "volume" => 0.7),
        "single_mattress" => array("title" => "Single Mattress", "volume" => 0.3),
        "king_bed_frame" => array("title" => "King Bed Frame", "volume" => 1),
        "double_bed_frame" => array("title" => "Double Bed Frame", "volume" => 0.6),
        "queen_bed_frame" => array("title" => "Queen Bed Frame", "volume" => 0.7),
        "single_bed_frame" => array("title" => "Single Bed Frame", "volume" => 0.3),
        "bed_king_and_mattress" => array("title" => "Bed (King and Mattress)", "volume" => 2),
        "bed_double_and_mattress" => array("title" => "Bed (Double and Mattress)", "volume" => 1.2),
        "bed_queen_and_mattress" => array("title" => "Bed (Queen and Mattress)", "volume" => 1.4),
        "bed_single_and_mattress" => array("title" => "Bed (Single and Mattress)", "volume" => 0.6),
        "bedside_table" => array("title" => "Bedside table", "volume" => 0.15, "synonyms" => "nightstand"),
        "bookcase" => array("title" => "Bookcase", "volume" => 1, "synonyms" => "shelf,shelves"),
        "bunks" => array("title" => "Bunks", "volume" => 1.24, "synonyms" => "bed"),
        "chair" => array("title" => "Chair", "volume" => 0.15, "synonyms" => "seat"),
        "change_table" => array("title" => "Change Table", "volume" => 0.8),
        "chest_of_drawers" => array("title" => "Chest of Drawers", "volume" => 0.5, "synonyms" => "bureau,dresser,tallboy,tall boy"),
        "tallboy" => array("title" => "Tallboy", "volume" => 0.5, "synonyms" => "chest of drawers,bureau,dresser,tall boy"),
        "cot" => array("title" => "Cot", "volume" => 0.5),
        "portacot" => array("title" => "Portacot", "volume" => 0.1),
        "cupboard_bedroom" => array("title" => "Cupboard", "volume" => 1, "synonyms" => "cabinet"),
        "desk" => array("title" => "Desk", "volume" => 1),
        "dressing_table" => array("title" => "Dressing Table", "volume" => 1),
        "headboard" => array("title" => "Headboard", "volume" => 0.3),
        "large_toys" => array("title" => "Large Toys", "volume" => 0.8),
        "mirror_small" => array("title" => "Mirror (Small)", "volume" => 0.1),
        "mirror_large" => array("title" => "Mirror (Large)", "volume" => 0.3),
        "play_pen" => array("title" => "Play Pen", "volume" => 2.2),
        "pram" => array("title" => "Pram", "volume" => 1.2, "synonyms" => "stroller"),
        "stool_bedroom" => array("title" => "Stool", "volume" => 0.15),
        "suitcase" => array("title" => "Suitcase", "volume" => 0.3),
        "table_lamp" => array("title" => "Table Lamp", "volume" => 0.15, "synonyms" => "light"),
        "toy_box_chest" => array("title" => "Toy Box / Chest", "volume" => 0.25),
        "wardrobe_large" => array("title" => "Wardrobe (Large)", "volume" => 1),
        "wardrobe_small" => array("title" => "Wardrobe (Small)", "volume" => 0.5),
        "water_bed" => array("title" => "Water Bed", "volume" => 2),
    ), "Lounge" => array(
        "air_conditioner" => array("title" => "Air Conditioner", "volume" => 0.25),
        "bean_bag" => array("title" => "Bean Bag", "volume" => 0.4),
        "bookcase_lounge" => array("title" => "Bookcase", "volume" => 1, "synonyms" => "shelf,shelves"),
        "china_cabinet" => array("title" => "China Cabinet", "volume" => 1),
        "cocktail_cabinet" => array("title" => "Cocktail Cabinet", "volume" => 0.8),
        "coffee_table" => array("title" => "Coffee Table", "volume" => 0.28),
        "electric_organ" => array("title" => "Electric Organ", "volume" => 1),
        "filing_cabinet" => array("title" => "Filing Cabinet", "volume" => 0.85),
        "firescreen_and_fire_set" => array("title" => "Firescreen and Fire Set", "volume" => 0.1),
        "fan" => array("title" => "Fan", "volume" => 0.1),
        "guitar" => array("title" => "Guitar", "volume" => 0.15),
        "heater" => array("title" => "Heater - Indoor", "volume" => 0.1),
        "lounge_2_seater" => array("title" => "Lounge (2 Seater)", "volume" => 1.7, "synonyms" => "couch,sofa,settee"),
        "lounge_3_seater" => array("title" => "Lounge (3 Seater)", "volume" => 2.2, "synonyms" => "couch,sofa,settee"),
        "lounge_chair" => array("title" => "Lounge Chair", "volume" => 0.48, "synonyms" => "couch,sofa,settee"),
        "lounge_modular" => array("title" => "Lounge Modular", "volume" => 3.5, "synonyms" => "couch,sofa,settee"),
        "ottoman_pouffe" => array("title" => "Ottoman Pouffe", "volume" => 0.2),
        "piano_stool" => array("title" => "Piano Stool", "volume" => 0.15),
        "grand_piano" => array("title" => "Grand Piano", "volume" => 3),
        "piano" => array("title" => "Piano", "volume" => 2),
        "pool_table" => array("title" => "Pool Table", "volume" => 2.4),
        "rocker_recliner_chair" => array("title" => "Rocker Recliner Chair", "volume" => 0.9),
        "roll_top_desk" => array("title" => "Roll Top Desk", "volume" => 1),
        "standard_lamp" => array("title" => "Standard Lamp", "volume" => 0.14),
        "stereo_and_speakers" => array("title" => "Stereo and Speakers", "volume" => 0.4),
        "tv_small" => array("title" => "TV (Small)", "volume" => 0.3, "synonyms" => "television"),
        "tv_medium" => array("title" => "TV (Medium)", "volume" => 0.4, "synonyms" => "television"),
        "tv_large" => array("title" => "TV (Large)", "volume" => 0.5, "synonyms" => "television"),
        "tv_stereo_cabinet" => array("title" => "TV Stereo Cabinet", "volume" => 0.8),
        "dvd_player" => array("title" => "DVD player", "volume" => 0.1, "synonyms" => "cd player,video player,vcr,bluray player,blu ray player"),
        "wall_unit" => array("title" => "Wall Unit", "volume" => 1),
        "treadmill" => array("title" => "Treadmill", "volume" => 2)
    ), "Kitchen" => array(
        "cabinet" => array("title" => "Cabinet", "volume" => 0.85),
        "chair_kitchen" => array("title" => "Chair", "volume" => 0.15),
        "cupboard" => array("title" => "Cupboard", "volume" => 1),
        "dishwasher" => array("title" => "Dishwasher", "volume" => 0.5),
        "freezer" => array("title" => "Freezer", "volume" => 1),
        "high_chair" => array("title" => "High Chair", "volume" => 0.15),
        "kitchen_tidy" => array("title" => "Kitchen Tidy", "volume" => 0.2),
        "microwave" => array("title" => "Microwave", "volume" => 0.15),
        "fridge_small" => array("title" => "Fridge (Small)", "volume" => 0.8),
        "fridge_medium" => array("title" => "Fridge (Medium)", "volume" => 1),
        "fridge_large" => array("title" => "Fridge (Large)", "volume" => 1.2),
        "fridge_2_door" => array("title" => "Fridge (2 door)", "volume" => 1.6),
        "stool" => array("title" => "Stool", "volume" => 0.15),
        "table_medium" => array("title" => "Table (Medium)", "volume" => 1),
        "table_large" => array("title" => "Table (Large)", "volume" => 2)
    ), "Dining" => array(
        "bar_or_crystal_cabinet" => array("title" => "Bar or Crystal Cabinet", "volume" => 1),
        "bookcase_dining" => array("title" => "Bookcase", "volume" => 1, "synonyms" => "shelf,shelves"),
        "buffet" => array("title" => "Buffet", "volume" => 0.8, "synonyms" => "sideboard"),
        "chairs" => array("title" => "Chairs", "volume" => 0.15),
        "dining_table" => array("title" => "Dining Table", "volume" => 2),
        "traymobile" => array("title" => "Traymobile", "volume" => 0.2)
    ), "Laundry" => array(
        "brooms_mop" => array("title" => "Brooms / Mop", "volume" => 0.15),
        "clothes_basket" => array("title" => "Clothes Basket", "volume" => 0.1, "synonyms" => "hamper"),
        "clothes_horse_airer" => array("title" => "Clothes Horse Airer", "volume" => 0.05),
        "cupboard_laundry" => array("title" => "Cupboard", "volume" => 0.8, "synonyms" => "cabinet"),
        "tumble_drier_cabinet" => array("title" => "Tumble Dryer Cabinet", "volume" => 0.5),
        "tumble_drier" => array("title" => "Tumble Dryer", "volume" => 0.5, "synonyms" => "drier,dryer"),
        "ironing_board" => array("title" => "Ironing Board", "volume" => 0.1),
        "laundry_trolley" => array("title" => "Laundry Trolley", "volume" => 0.1),
        "sewing_machine" => array("title" => "Sewing Machine", "volume" => 0.6),
        "stool_laundry" => array("title" => "Stool", "volume" => 0.15),
        "laundry_table" => array("title" => "Table", "volume" => 0.5),
        "vacuum_cleaner" => array("title" => "Vacuum Cleaner", "volume" => 0.2),
        "washing_machine_top_loader" => array("title" => "Washing Machine (Top Load)", "volume" => 0.5),
        "washing_machine_front_loader" => array("title" => "Washing Machine (Front Load)", "volume" => 0.7),
        "steam_mop" => array("title" => "Steam Mop", "volume" => 0.2)
    ), "Office" => array(
        "computer" => array("title" => "Computer", "volume" => 0.28),
        "desk_office" => array("title" => "Desk", "volume" => 1),
        "office_chair" => array("title" => "Office Chair", "volume" => 0.5),
        "office_lamp" => array("title" => "Lamp", "volume" => 0.14),
        "printer" => array("title" => "Printer", "volume" => 0.3)
    ), "Hall" => array(
        "carpets_and_rugs" => array("title" => "Carpets and Rugs", "volume" => 0.2),
        "grand_father_clock" => array("title" => "Grand Father Clock", "volume" => 0.5),
        "hall_stand_table" => array("title" => "Hall Stand Table", "volume" => 0.28, "synonyms" => "sideboard"),
        "hat_rack_stand" => array("title" => "Hat Rack Stand", "volume" => 0.14),
        "pictures_mirror" => array("title" => "Pictures / Mirror", "volume" => 0.15)
    ), "Garage" => array(
        "aquarium_small" => array("title" => "Aquarium (Small)", "volume" => 0.4, "synonyms" => "tank,terrarium,fish tank"),
        "aquarium_large" => array("title" => "Aquarium (Large)", "volume" => 1, "synonyms" => "tank,terrarium,fish tank"),
        "barbeque" => array("title" => "Barbeque", "volume" => 1, "synonyms" => "grill,bbq"),
        "webber" => array("title" => "Webber", "volume" => 0.5, "synonyms" => "grill,bbq"),
        "kennel" => array("title" => "Dog Kennel", "volume" => 0.6, "synonyms" => "dog house, dog kennel"),
        "dog_bed" => array("title" => "Dog Bed", "volume" => 0.2),
        "beach_umbrella" => array("title" => "Beach Umbrella", "volume" => 0.14),
        "bicycle" => array("title" => "Bicycle", "volume" => 0.3, "synonyms" => "bike"),
        "boogie_board" => array("title" => "Boogie Board", "volume" => 0.1, "synonyms" => "body board, boogieboard, bodyboard"),
        "card_table" => array("title" => "Card Table", "volume" => 0.15),
        "chair_garage" => array("title" => "Chair", "volume" => 0.1, "synonyms" => "seat"),
        "child_table_and_chairs" => array("title" => "Child Table and Chairs", "volume" => 0.1),
        "fishing_rod_" => array("title" => "Fishing Rod", "volume" => 0.2),
        "esky" => array("title" => "Esky", "volume" => 0.5, "synonyms" => "cooler"),
        "folding_chair" => array("title" => "Folding Chair", "volume" => 0.21, "synonyms" => "camp chair"),
        "garbage_bin" => array("title" => "Garbage Bin", "volume" => 0.2, "synonyms" => "trash can"),
        "garden_seat" => array("title" => "Garden Seat", "volume" => 0.4, "synonyms" => "bench"),
        "garden_tools_and_hose" => array("title" => "Garden Tools and Hose", "volume" => 0.3),
        "golf_bag_and_buggy" => array("title" => "Golf Bag and Buggy", "volume" => 2),
        "heater_outdoor" => array("title" => "Heater - Outdoor", "volume" => 0.8),
        "jetski" => array("title" => "Jetski", "volume" => 2),
        "ladder" => array("title" => "Ladder", "volume" => 0.3),
        "lawn_mower" => array("title" => "Lawn Mower", "volume" => 1),
        "whipper_snipper" => array("title" => "Whipper Snipper", "volume" => 0.2),
        "outdoor_table" => array("title" => "Outdoor Table", "volume" => 1),
        "outdoor_set" => array("title" => "Garden set (Small)", "volume" => 1, "synonyms" => "garden set, breakfast table, outdoor setting, outdoor set"),
        "outdoor_set_large" => array("title" => "Garden set (Large)", "volume" => 2.6, "synonyms" => "garden set, breakfast table, outdoor setting, outdoor set"),
        "rocking_horse" => array("title" => "Rocking Horse", "volume" => 0.85),
        "swing_dismantled" => array("title" => "Swing (Dismantled)", "volume" => 1),
        "tool_box" => array("title" => "Tool Box", "volume" => 0.5),
        "tool_cupboard" => array("title" => "Tool Cupboard", "volume" => 0.1),
        "trampoline_dismantled" => array("title" => "Trampoline (Dismantled)", "volume" => 0.58),
        "tricycle" => array("title" => "Tricycle", "volume" => 1),
        "rods" => array("title" => "Rods", "volume" => 0.1),
        "wheel_barrow" => array("title" => "Wheel Barrow", "volume" => 0.58),
        "work_bench" => array("title" => "Work Bench", "volume" => 1),
        "pot_plant_small" => array("title" => "Pot Plant (Small)", "volume" => 0.3),
        "pot_plant_large" => array("title" => "Pot Plant (Large)", "volume" => 0.7),
        "surfboard" => array("title" => "Surfboard", "volume" => 0.3),
        "snowboard" => array("title" => "Snowboard", "volume" => 0.5),
        "swag" => array("title" => "Swag", "volume" => 0.35),
        "tent" => array("title" => "Tent", "volume" => 0.2),
        "table_tennis" => array("title" => "Table Tennis Table", "volume" => 0.5, "synonyms" => "ping pong, ping pong table"),
        "weights_bench" => array("title" => "Weights Bench", "volume" => 2),
        "weights_set" => array("title" => "Weights Set", "volume" => 0.5)
    ), "Cartons" => array(
        "removalist_cartons" => array("title" => "Removalist Cartons", "volume" => 0.15),
        "book_boxes" => array("title" => "Book Boxes", "volume" => 0.1),
        "picture_boxes" => array("title" => "Picture Boxes", "volume" => 0.1),
        "portarobes" => array("title" => "Portarobes", "volume" => 0.3),
        "plastic_tub" => array("title" => "Plastic Tub", "volume" => 0.1, "synonyms" => "plastic container"),
        "striped_bags" => array("title" => "Striped Bags", "volume" => 0.15),
        "flat_pack_sm" => array("title" => "Flat-packed Furniture (Small)", "volume" => 0.15),
        "flat_pack_md" => array("title" => "Flat-packed Furniture (Medium)", "volume" => 0.30),
        "flat_pack_lg" => array("title" => "Flat-packed Furniture (Large)", "volume" => 0.45)
    ),
    "Apartment" => array(
        "studio_apartment" => array("title" => "Studio apartment", "volume" => 8),
        "1_bedroom_apartment" => array("title" => "1 bedroom apartment", "volume" => 15),
        "2_bedroom_apartment" => array("title" => "2 bedroom apartment", "volume" => 23),
        "3_bedroom_apartment" => array("title" => "2 bedroom apartment", "volume" => 32),
        "4_bedroom_apartment" => array("title" => "4 bedroom apartment", "volume" => 42),
    ),
    "House" => array(
        # "1_bedroom_house" => array("title" => "1 bedroom house", "volume" => 15),
        "2_bedroom_house" => array("title" => "2 bedroom house", "volume" => 26),
        "3_bedroom_house" => array("title" => "2 bedroom house", "volume" => 35),
        "4_bedroom_house" => array("title" => "4 bedroom house", "volume" => 48),
        "5_bedroom_house" => array("title" => "4 bedroom house", "volume" => 55)
    ),
];
